---
# Setup OCP4 Helper Node

- hosts: all
  vars_files:
    - ../vars/main.yml
    - ../vars/ports.yml
  handlers:
  - import_tasks: ../handlers/main.yml
    
  tasks:
  - name: generate ssh keys
    import_tasks: generate_ssh_keys.yaml
    when: ssh_gen_key

  - name: set setup facts
    include: set_facts_.yaml

  - name: Install needed packages
    package:
      name: "{{ packages }}"
      state: present


  - name: Preparing OCP client
    when: ocp_client is defined
    block:
    - name: Downloading OCP4 client
      get_url:
        url: "{{ ocp_client }}"
        dest: /usr/local/src/openshift-client-linux.tar.gz

    - name: Unarchiving OCP4 client
      unarchive:
        src: /usr/local/src/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes


  - name: Setup Local Registry
    when: setup_registry.deploy
    block:
    - name: Install registry packages
      package:
        name: "{{ registry }}"
        state: present

    - name: Setup Registry
      import_tasks: setup_registry.yaml
